// utils/championImages.js
export function getChampionImage(championName) {
    // Mapeo de nombres de campeones a nombres de archivo de imagen
    const imageMap = {
        'Aatrox': 'aatrox.webp',
        'Ahri': 'ahri.webp',
        'Akali': 'akali.webp',
        'Akshan': 'akshan.webp',
        'Alistar': 'alistar.webp',
        'Ambessa': 'ambessa.webp',
        'Amumu': 'amumu.webp',
        'Anivia': 'anivia.webp',
        'Annie': 'annie.webp',
        'Aphelios': 'aphelios.webp',
        'Ashe': 'ashe.webp',
        'Aurelion Sol': 'aurelionsol.webp',
        'Aurora': 'aurora.webp',
        'Azir': 'azir.webp',
        'Bardo': 'bard.webp',
        'Bel\'Veth': 'belveth.webp',
        'Blitzcrank': 'blitzcrank.webp',
        'Brand': 'brand.webp',
        'Braum': 'braum.webp',
        'Briar': 'briar.webp',
        'Caitlyn': 'caitlyn.webp',
        'Camille': 'camille.webp',
        'Cassiopeia': 'cassiopeia.webp',
        'Cho\'Gath': 'chogath.webp',
        'Corki': 'corki.webp',
        'Darius': 'darius.webp',
        'Diana': 'diana.webp',
        'Dr. Mundo': 'drmundo.webp',
        'Draven': 'draven.webp',
        'Ekko': 'ekko.webp',
        'Elise': 'elise.webp',
        'Evelynn': 'evelynn.webp',
        'Ezreal': 'ezreal.webp',
        'Fiddlesticks': 'fiddlesticks.webp',
        'Fiora': 'fiora.webp',
        'Fizz': 'fizz.webp',
        'Galio': 'galio.webp',
        'Gangplank': 'gangplank.webp',
        'Garen': 'garen.webp',
        'Gnar': 'gnar.webp',
        'Gragas': 'gragas.webp',
        'Graves': 'graves.webp',
        'Gwen': 'gwen.webp',
        'Hecarim': 'hecarim.webp',
        'Heimerdinger': 'heimerdinger.webp',
        'Hwei': 'hwei.webp',
        'Illaoi': 'illaoi.webp',
        'Irelia': 'irelia.webp',
        'Ivern': 'ivern.webp',
        'Janna': 'janna.webp',
        'Jarvan IV': 'jarvaniv.webp',
        'Jax': 'jax.webp',
        'Jayce': 'jayce.webp',
        'Jhin': 'jhin.webp',
        'Jinx': 'jinx.webp',
        'K\'Sante': 'ksante.webp',
        'Kai\'Sa': 'kaisa.webp',
        'Kalista': 'kalista.webp',
        'Karma': 'karma.webp',
        'Karthus': 'karthus.webp',
        'Kassadin': 'kassadin.webp',
        'Katarina': 'katarina.webp',
        'Kayle': 'kayle.webp',
        'Kayn': 'kayn.webp',
        'Kennen': 'kennen.webp',
        'Kha\'Zix': 'khazix.webp',
        'Kindred': 'kindred.webp',
        'Kled': 'kled.webp',
        'Kog\'Maw': 'kogmaw.webp',
        'LeBlanc': 'leblanc.webp',
        'Lee Sin': 'leesin.webp',
        'Leona': 'leona.webp',
        'Lillia': 'lillia.webp',
        'Lissandra': 'lissandra.webp',
        'Lucian': 'lucian.webp',
        'Lulu': 'lulu.webp',
        'Lux': 'lux.webp',
        'Maestro Yi': 'masteryi.webp',
        'Malphite': 'malphite.webp',
        'Malzahar': 'malzahar.webp',
        'Maokai': 'maokai.webp',
        'Mel': 'mel.webp',
        'Milio': 'milio.webp',
        'Miss Fortune': 'missfortune.webp',
        'Mordekaiser': 'mordekaiser.webp',
        'Morgana': 'morgana.webp',
        'Naafiri': 'naafiri.webp',
        'Nami': 'nami.webp',
        'Nasus': 'nasus.webp',
        'Nautilus': 'nautilus.webp',
        'Neeko': 'neeko.webp',
        'Nidalee': 'nidalee.webp',
        'Nilah': 'nilah.webp',
        'Nocturne': 'nocturne.webp',
        'Nunu y Willump': 'nunu.webp',
        'Olaf': 'olaf.webp',
        'Orianna': 'orianna.webp',
        'Ornn': 'ornn.webp',
        'Pantheon': 'pantheon.webp',
        'Poppy': 'poppy.webp',
        'Pyke': 'pyke.webp',
        'Qiyana': 'qiyana.webp',
        'Quinn': 'quinn.webp',
        'Rakan': 'rakan.webp',
        'Rammus': 'rammus.webp',
        'Rek\'Sai': 'reksai.webp',
        'Rell': 'rell.webp',
        'Renata Glasc': 'renata.webp',
        'Renekton': 'renekton.webp',
        'Rengar': 'rengar.webp',
        'Riven': 'riven.webp',
        'Rumble': 'rumble.webp',
        'Ryze': 'ryze.webp',
        'Samira': 'samira.webp',
        'Sejuani': 'sejuani.webp',
        'Senna': 'senna.webp',
        'Seraphine': 'seraphine.webp',
        'Sett': 'sett.webp',
        'Shaco': 'shaco.webp',
        'Shen': 'shen.webp',
        'Shyvana': 'shyvana.webp',
        'Singed': 'singed.webp',
        'Sion': 'sion.webp',
        'Sivir': 'sivir.webp',
        'Skarner': 'skarner.webp',
        'Smolder': 'smolder.webp',
        'Sona': 'sona.webp',
        'Soraka': 'soraka.webp',
        'Swain': 'swain.webp',
        'Sylas': 'sylas.webp',
        'Syndra': 'syndra.webp',
        'Tahm Kench': 'tahmkench.webp',
        'Taliyah': 'taliyah.webp',
        'Talon': 'talon.webp',
        'Taric': 'taric.webp',
        'Teemo': 'teemo.webp',
        'Thresh': 'thresh.webp',
        'Tristana': 'tristana.webp',
        'Trundle': 'trundle.webp',
        'Tryndamere': 'tryndamere.webp',
        'Twisted Fate': 'twistedfate.webp',
        'Twitch': 'twitch.webp',
        'Udyr': 'udyr.webp',
        'Urgot': 'urgot.webp',
        'Varus': 'varus.webp',
        'Vayne': 'vayne.webp',
        'Veigar': 'veigar.webp',
        'Vel\'Koz': 'velkoz.webp',
        'Vex': 'vex.webp',
        'Vi': 'vi.webp',
        'Viego': 'viego.webp',
        'Viktor': 'viktor.webp',
        'Vladimir': 'vladimir.webp',
        'Volibear': 'volibear.webp',
        'Warwick': 'warwick.webp',
        'Wukong': 'monkeyking.webp',
        'Xayah': 'xayah.webp',
        'Xerath': 'xerath.webp',
        'Xin Zhao': 'xinzhao.webp',
        'Yasuo': 'yasuo.webp',
        'Yone': 'yone.webp',
        'Yorick': 'yorick.webp',
        'Yunara': 'yunara.webp',
        'Yuumi': 'yuumi.webp',
        'Zac': 'zac.webp',
        'Zed': 'zed.webp',
        'Zeri': 'zeri.webp',
        'Ziggs': 'ziggs.webp',
        'Zilean': 'zilean.webp',
        'Zoe': 'zoe.webp',
        'Zyra': 'zyra.webp'
    };

    return imageMap[championName] || 'default.webp';
}

export function getChampionTitle(championName) {
    // Podemos expandir esto más tarde con títulos reales
    const titles = {
        'Aatrox': 'La Espada Darkin',
        'Ahri': 'La Mujer Zorro de Nueve Colas',
        'Ashe': 'La Arquera de Hielo',
        'Darius': 'La Mano de Noxus'
        // ... agregar más títulos según necesites
    };
    
    return titles[championName] || 'Campeón de League of Legends';
}